### ISSUE TITLE
Panel operation fails with the N menu open, only when active tab is HugeMenance

### ISSUE THREAD

**Issue by rubberduck9999** [hugemenace/nd#118]
When I have the N menu open and the active tab is the ND / HugeMenance, then the panel operation fails, giving the following error message: ```
Python: Traceback (most recent call last):
  File "C:\Users\sebas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\nd\lib\base_operator.py", line 95, in modal
    self.operate(context)
  File "C:\Users\sebas\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\nd\sketch\panel.py", line 188, in operate
    bmesh.ops.delete(self.panel_bm, geom=self.panel_bm.verts, context='VERTS')
                                         ^^^^^^^^^^^^^^^^^^^
ReferenceError: BMesh data of type BMesh has been removed
```
I tried first hiding the menu by pressing n, the result, the panel operation suddenly worked, also when I had the n menu open but any other tab active

**Comment by tristan-hm** [comment]
Thanks for reporting. I'm investigating another issue with the panel operator that may be related to this. I hope to push out a fix in the next release.
