### ISSUE TITLE
Error when cancelling the array operator

### ISSUE THREAD

**Issue by tristan-hm** [hugemenace/nd#127]
```
Python: Traceback (most recent call last):
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\nd\lib\base_operator.py", line 67, in invoke
    return self.do_invoke(context, event)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\nd\replicate\array_cubed.py", line 179, in do_invoke
    self.operate(context)
  File "C:\Users\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\nd\replicate\array_cubed.py", line 239, in operate
    array, count, offset, relative = conf
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by tristan-hm** [comment]
Unable to replicate at this point. I am happy to reopen if this issue resurfaces.
